# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 09:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
