# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenurl',
            name='shortcode',
            field=models.CharField(default='', max_length=15),
        ),
    ]
