# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shortenurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='shortcode',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
