# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_shortenurl_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenurl',
            name='id',
        ),
        migrations.AlterField(
            model_name='shortenurl',
            name='shortcode',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
